# Generated by Django 3.2.21 on 2023-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=1000000000, null=True)),
                ('product_title', models.CharField(max_length=1000000000, null=True)),
                ('product_description', models.CharField(max_length=1000000000, null=True)),
                ('weight', models.CharField(max_length=1000000000, null=True)),
                ('package', models.CharField(max_length=1000000000, null=True)),
                ('price_per_pack', models.CharField(max_length=1000000000, null=True)),
                ('price_per_unit', models.CharField(max_length=1000000000, null=True)),
                ('image_file', models.FileField(default='None', null=True, upload_to='media')),
                ('make', models.CharField(max_length=1000000000, null=True)),
                ('market', models.CharField(max_length=1000000000, null=True)),
                ('model', models.CharField(max_length=1000000000, null=True)),
                ('body', models.CharField(max_length=1000000000, null=True)),
                ('year', models.CharField(max_length=1000000000, null=True)),
                ('suspension_type', models.CharField(choices=[('Front-Suspension', 'Front-Suspension'), ('Rear-Suspension', 'Rear-Suspension')], max_length=1000000000, null=True)),
                ('product_category', models.CharField(choices=[('Featured', 'Featured'), ('Popular', 'Popular'), ('Best-Seller', 'Best-Seller'), ('New-Arrival', 'New-Arrival'), ('Deal-Zome', 'Deal-Zone')], max_length=1000000000, null=True)),
            ],
        ),
    ]
