# Generated by Django 3.2.21 on 2023-09-30 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20231001_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='submission_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
