# Generated by Django 3.2.21 on 2023-10-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='search_image_file',
            field=models.FileField(default='None', null=True, upload_to='media'),
        ),
    ]
