# Generated by Django 3.2.21 on 2023-10-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_productdata_search_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='none', max_length=20)),
                ('coin_ids', models.ManyToManyField(to='website.ProductData')),
            ],
        ),
    ]
