# Generated by Django 3.2.21 on 2023-10-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_category',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Popular', 'Popular'), ('Best-Seller', 'Best-Seller'), ('New-Arrival', 'New-Arrival'), ('Deal-Zone', 'Deal-Zone')], max_length=1000000000, null=True),
        ),
    ]
