# Generated by Django 3.2.21 on 2023-10-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_productdata_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='none', max_length=20)),
                ('confirmation_no', models.CharField(max_length=1000000000, null=True)),
                ('payment_proof', models.FileField(default='None', null=True, upload_to='payment_proof')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], max_length=1000000000, null=True)),
                ('coin_ids', models.ManyToManyField(to='website.ProductData')),
            ],
        ),
    ]
