# Generated by Django 3.2.21 on 2023-10-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_order_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000000000, null=True)),
                ('last_name', models.CharField(max_length=1000000000, null=True)),
                ('bank_name', models.CharField(max_length=1000000000, null=True)),
                ('account_no', models.CharField(max_length=1000000000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zelle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=1000000000, null=True)),
                ('email', models.CharField(max_length=1000000000, null=True)),
                ('phone_no', models.CharField(max_length=1000000000, null=True)),
            ],
        ),
    ]
