# Generated by Django 3.2.21 on 2023-10-13 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_order_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='submission_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
