# Generated by Django 3.2.21 on 2023-10-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_contact_us_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='bushing_no',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='status',
            field=models.CharField(choices=[('in-stock', 'in-stock'), ('out-of-stock', 'out-of-stock')], max_length=1000000000, null=True),
        ),
    ]
