# Generated by Django 3.0.8 on 2023-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20231013_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bank_details',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zelle_details',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
