# Generated by Django 3.2.21 on 2023-10-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20231015_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=1000000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_no',
            field=models.CharField(max_length=1000000000, null=True),
        ),
    ]
