# Generated by Django 3.2.21 on 2023-10-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20231015_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(default='None', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='image_file',
            field=models.ImageField(default='None', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='search_image_file',
            field=models.ImageField(default='None', null=True, upload_to='media'),
        ),
    ]
