# Generated by Django 3.2.23 on 2024-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_user_discount_table_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'bank'), ('crypto', 'crypto')], max_length=1000000000, null=True),
        ),
    ]
